source 'https://rubygems.org'
ruby '2.6.10'

gem 'httparty', '~> 0.21.0'
gem 'optparse', '~> 0.3.1'
gem 'csv', '~> 3.2', '>= 3.2.7'
gem 'json', '~> 2.1.0'
gem 'rspec', '~> 3.12'
gem 'dotenv', '~> 2.8', '>= 2.8.1'